### PR TITLE
Debounce submit when logging/copying food & saving/updating custom food

### PR DESCRIPTION
**Pull request by Xebeth**

### CODE REVIEW

**Comment by jlai** [comment]
Good catch on this needing to be debounced (and probably other places too).

It's somewhat commonly misused, but a timed `debounce` is not the best way to prevent duplicate form submissions. The request to the server could take more than 500 milliseconds.

(Side note: if you ever find yourself wanting to use lodash, use [es-toolkit](https://es-toolkit.slash.page/) instead; it's a more modern alternative)

Instead, let's make the onSubmit function async, because `react-hook-form` has support for async submit functions and blocks further calls to onSubmit while it's pending.

```ts
  const logFood = async (values: CreateFoodLogFormData) => {
    const { food, servingSize, mealType, daySource } = values;

    if (!food || !servingSize || isPending) {
      return;
    }

    await createFood({
      foodId: food.foodId,
      mealTypeId: mealType,
      day: daySource === "today" ? dayjs() : linkedDay,
      amount: servingSize.amount,
      unitId: servingSize.unit.id,
    });

    toast.success(`Logged food: ${food.name}`);
    formContext.reset({
      food: null,
      servingSize: null,

      // Stay on existing day and mealType
      mealType: values.mealType,
      daySource,
    });
  };
```

(This also removes the useCallback wrapper because it turns out it's [not really necessary](https://kentcdodds.com/blog/usememo-and-usecallback) is most cases).

We can also check the mutation status using `isPending` from `useMutation`:

```ts
const { mutateAsync: createFood, isPending: isSubmitPending } = useMutation(
  buildCreateFoodLogMutation(queryClient)
);
```

This is useful for 1) actions that don't use `FormContainer`, and 2) showing the state of the action to the user using a spinner:

```ts
<LoadingButton
  type="submit"
  loading={isSubmitPending}
  disabled={!watch("food") || !watch("servingSize")}
>
  Do stuff
</LoadingButton>
```

**Comment by Xebeth** [comment]
There are certainly other places where this would be necessary but I only started modifying places where I was familiar with the code/UI (I've had a couple of accidental double submit in these places).
I guess I'll restart the branch then. I tried to search what was the best way to prevent double submit but I guess the example I found was a bit dated (there were much worse suggestions out there).

**Review by jlai — APPROVED** [review]

**Comment by jlai** [comment]
Created #71 to track cleaning up other buttons/actions that should be debounced.

**Comment by Xebeth** [comment]
I need to check the code again. Logging food only works once now.

**Review by jlai — APPROVED** [review]

**Pull request merged**
