### PR TITLE
Add select all/none checkboxes for each meal section + total

### PR DESCRIPTION
**Pull request by Xebeth**
image

### CODE REVIEW

**Comment by jlai** [comment]
Thanks for the PR! While testing, I noticed if you select a single food log entry, it marks the section + total as checked. Generally, it should only show the section checkbox as checked if all of the items in the section are checked.

If it's partly selected, the section checkbox should use the [indeterminate](https://mui.com/material-ui/react-checkbox/#indeterminate) state to show that the section only has some of the items selected. Per the [Material design spec](https://m3.material.io/components/checkbox/guidelines#26cbff1c-7a56-4237-b563-5593573e6cf4), clicking on the indeterminate checkbox for the section should mark the remaining items as selected.

**Comment by Xebeth** [comment]
I'll have a look but it's my first time doing React stuff (I'm more of a backend guy).

**Comment by Xebeth** [comment]
OK, I've updated the code now to follow your advice.

**Review by jlai — APPROVED** [review]
Looks good, thanks for the submission!

**Pull request merged**
